image: node:latest

stages:
  - lint
  - test
  - deploy

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    # Run ESLint
    - eslint index.js

deploy_production:
  image: google/cloud-sdk:alpine
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --project $PROJECT_ID functions deploy reply --runtime nodejs12 --trigger-http
  after_script:
    - rm /tmp/$CI_PIPELINE_ID.json
